version: 0.1
env:
  variables:
    commands:
      - echo exporting env variables.....
      - REACT_APP_USER_POOL_ID=${USER_POOL_ID}
      - REACT_APP_USER_CLIENT_ID=${CLIENT_ID}
      - echo $REACT_APP_USER_POOL_ID
phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build
artifacts:
  files:
    - "**/*"
  base-directory: build
